#!/bin/bash

if [ "$#" -eq 4 ]; then
    python3.6 -m autodse --src-dir $1 --work-dir $2 --config $3 --mode ${4}-dse
elif [ "$#" -eq 5 ]; then
    python3.6 -m autodse --src-dir $1 --work-dir $2 --config $3 --mode ${4}-dse --db $5
else
    echo "Usage: dse <project dir> <working dir> <config file> <fast|accurate> [<database file>]"
fi
