#!/bin/bash

if [ "$#" -eq 4 ]; then
    python3 -m autodse --src-dir $1 --work-dir $2 --config $3 --mode ${4}-dse
elif [ "$#" -eq 5 ]; then
    python3 -m autodse --src-dir $1 --work-dir $2 --config $3 --mode ${4}-dse --redis-port $5
elif [ "$#" -eq 6 ]; then
    python3 -m autodse --src-dir $1 --work-dir $2 --config $3 --mode ${4}-dse --redis-port $5 --db $6
else
    echo "Usage: dse <project dir> <working dir> <config file> <fast|accurate> [<redis port> <database file>]"
fi
